' Gambas module file

Public Sub prepararporconfiguracion() As DData
    
    Dim ubino As Integer = 0, codgno As Integer = 0, camno As Integer = 0
    Dim messageinfo As String = ""
    
    Dim configuracion As Settings 
    
    Dim datos As New DData
    
    ' esto solo funciona en entorno de desarrollo, cuanedo se lanza desde la ide
    If Not Exist(User.Home &/ ".asistenciatomar.conf") Then
        Try Copy "asistenciatomar.conf" To User.Home &/ ".asistenciatomar.conf"
    Endif
    
    ' en cualquier caso, esto solo es en desarrollo, en produccion, creara un archivo nuevo vacio
    configuracion = New Settings(user.Home & "/.asistenciatomar.conf")
    
    If IsNull(configuracion["dispositivo/camara", Null]) Then
        camno = 1
        datos.setCamaraDev("/dev/video0")
    Else
        datos.setCamaraDev(configuracion["dispositivo/camara"])
    End If  
    
    If IsNull(configuracion["dispositivo/tamano", Null]) Then
        Print "Tamano de camara no definido, usando por defecto minimo 320x240"
        datos.setCamaraSize("320x240")
    Else
        datos.setCamaraSize(configuracion["dispositivo/tamano"])
    End If  
    
    If IsNull(configuracion["conexion/tipo", Null]) Then
        Print "No definida conexcion local en archivo configuracion"
        datos.setContipoLo("sqlite3")
    Else
        datos.setContipoLo(configuracion["conexion/tipo"])
    End If  
    
    If IsNull(configuracion["origenes/op", Null]) Then
        Print "Origen OP no definido, usando devel por defecto"
        datos.setHostOP("37.10.254.20")
    Else
        datos.setHostOP(configuracion["origenes/op"])
    End If  
    
    If IsNull(configuracion["origenes/tipo", Null]) Then
        Print "No definido tipo de sincronismo, usando archivo csv"
        datos.setContipoOp("csv")
    Else
        datos.setContipoOp(configuracion["origenes/tipo"])
    End If  
    
    If IsNull(configuracion["origenes/compresa", Null]) Then
        Print "Compresion/cryto no definido, usandose y asumiendose por defecto"
        datos.setListaCompresa("bzlib2")
    Else
        datos.setListaCompresa(configuracion["origenes/compresa"])
    End If  
    
    If IsNull(configuracion["modalidad/enrolado", Null]) Then
        Print "Enrolado indirecto aprovacion por nomina usandose, no se definio en configuracon"
        datos.setModoDirecto("activacion")
    Else
        datos.setModoDirecto(configuracion["modalidad/enrolado"])
    End If  
    
    If IsNull(configuracion["modalidad/verificado", Null]) Then
        Print "Verificado de dedoy cara usandose, no definido en configuracion"
        datos.setModoVerificado("dedoycara")
    Else
        datos.setModoVerificado(configuracion["modalidad/verificado"])
    End If  
    
    If IsNull(configuracion["modalidad/control", Null]) Then
        Print "Control de acceso habilitado por defecto, redefina en la configuracion"
        datos.setAccessControlMode(True)
    Else
        Print "ver: " & configuracion["modalidad/control"]
        If Comp(configuracion["modalidad/control"], "T", gb.IgnoreCase) == 0 Or Comp(configuracion["modalidad/control"], "", gb.IgnoreCase) == 0 Then
            datos.setAccessControlMode(configuracion["modalidad/control"])
        Else
            Print "Control de acceso habilitado por defecto, redefina en la configuracion"
            datos.setAccessControlMode(True)
        Endif
    End If  
    
    If IsNull(configuracion["localidad/ubicacion", Null]) Then
        ubino = 1
        datos.setUbicacionLug("990")
    Else 
        datos.setUbicacionLug(configuracion["localidad/ubicacion"])
    Endif 
    
    If IsNull(configuracion["localidad/codger", Null]) Then
        codgno = 1
        datos.setUbicacionUsr("999")
    Else 
        datos.setUbicacionUsr(configuracion["localidad/codger"])
    Endif 
    
    If codgno == 1 Or camno == 1 Or ubino == 1 Then
        messageinfo = "Se encontraron los sigueintes problemas en el archivo de configuracion:"
        If camno == 1 Then
            messageinfo = messageinfo & "\n* Camara no esta definida en el archivo de configuracion"
        Endif
        If ubino == 1 Then
            messageinfo = messageinfo & "\n* Ubicacion no definida en el archivo de configuracion"
        Endif
        If codgno == 1 Then
            messageinfo = messageinfo & "\n* Codigo de ubicacion no definida en el archivo de configuracion"
        Endif
        Message.Info(messageinfo)
    Endif
    
    '     #enrolado can be "directo" Or "activacion"
    ' enrolado = "directo"
    ' #verificado can be "dedo", "cara or " dedoycara ""
    ' verificado = "dedoycara"
    ' #modo can be "demo", "auto" Or "connodo", the "connodo" need a post5gresql DB working ina valid ip
    ' modo = "auto"
    Return datos
    
End
